# Generated by Django 5.2.16 on 2026-07-21 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='List of trigger keywords')),
                ('response_text', models.TextField()),
                ('is_default_fallback', models.BooleanField(default=False, help_text='Check if this is a random fallback response')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(help_text="Unique identifier e.g. 'variables'", max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('indicator', models.CharField(help_text="e.g. 'Topic 1'", max_length=50)),
                ('tanglish_exp', models.TextField(help_text='Tanglish explanation with HTML formatting')),
                ('english_exp', models.TextField(help_text='English explanation with HTML formatting')),
                ('initial_code', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list, help_text='List of quiz option strings')),
                ('correct_index', models.PositiveIntegerField(default=0)),
                ('correct_headline', models.CharField(max_length=200)),
                ('correct_text', models.TextField()),
                ('correct_svg', models.TextField(help_text='SVG HTML code for correct reaction')),
                ('incorrect_headline', models.CharField(max_length=200)),
                ('incorrect_text', models.TextField()),
                ('incorrect_svg', models.TextField(help_text='SVG HTML code for incorrect reaction')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='kadhai.lesson')),
            ],
        ),
    ]
