# Generated by Django 5.2.16 on 2026-08-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadhai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotresponse',
            options={'verbose_name_plural': 'Chatbot Responses'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
