# Generated by Django 5.2.16 on 2026-08-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadhai', '0002_alter_chatbotresponse_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tamil_exp',
            field=models.TextField(blank=True, default='', help_text='Pure Tamil explanation with HTML formatting'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='indicator',
            field=models.CharField(default='BEGINNER', help_text='e.g., BEGINNER, INTERMEDIATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='initial_code',
            field=models.TextField(blank=True, default='', help_text='Starting Python code snippet'),
        ),
    ]
